const CONTENT_TYPE_HEADER = "Content-Type";
const CONTENT_LENGTH_HEADER = "Content-Length";
const CONNECTION_HEADER = "Connection";
const TRANSFER_ENCODING = "Transfer-Encoding";
const CONTENT_DISPOSITION = 'Content-Disposition';
const CONTENT_ENCODING = 'Content-Encoding';
const ACCEPT_ENCODING = 'Accept-Encoding';

module.exports = {ACCEPT_ENCODING, CONTENT_ENCODING, CONTENT_TYPE_HEADER, CONTENT_LENGTH_HEADER, CONNECTION_HEADER, TRANSFER_ENCODING, CONTENT_DISPOSITION};